name: Update F1 Data

on:
  workflow_dispatch:
    inputs:
      round:
        description: 'Race round number'
        required: true

jobs:
  f1-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas fastf1 scikit-learn xgboost

      - name: Run F1 Data Script
        run: |
          cd Website/f1nalyse/public/data
          python f1.py storeData ${{ github.event.inputs.round }}
          python f1.py updateData
          python f1.py train ${{ github.event.inputs.round }}

      - name: Commit updated CSVs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Website/f1nalyse/public/data/*.csv
          git commit -m "Update F1 data" || echo "No changes to commit"
          git push
